keikoproj/instance-manager

.travis.yml, Makefile
=> CI: Docker push fix

README.md, api/v1alpha1/instancegroup_types_test.go, test-bdd/testutil/helpers.go, test-bdd/testutil/igresource.go, test-bdd/testutil/wfresource.go
Adds build status, codecov, and goreport badges, fix typos
=> Readme: Add Badges

.github/CODEOWNERS, .travis.yml, Makefile, docs/04_instance-manager.yaml, docs/cloudformation/02_node-group-service-role.yaml, test-bdd/setup/setup.sh, test-bdd/testutil/helpers.go
Fixes #7 
- Runs functional test nightly (travis cronjob)
- Fixes a bug in BDD polling loop
- verified bdd test is passing
=> Travis improvements

test-bdd/main_test.go
Fixes #19 
- Make upgrade test path sequential
- Ran test locally
=> Fix Functional Test

controllers/provisioners/ekscloudformation/ekscloudformation_test.go
Contributes to #8 
- Added a few unit tests
=> Add unit-tests

README.md, codecov.yml
closes #21 
- Add slack & version badges
- codecov range change
=> Readme Changes

CHANGELOG.md, README.md, main.go
- Support for EKS managed node groups (#76)
- Use latest aws-sdk (#67, #76)
- Documentation fixes (#74)
=> release 0.5.0

test-bdd/main_test.go
=> removed unreachable code

.travis.yml, Dockerfile, go.mod
=> update golang version to 1.13.10

CHANGELOG.md, README.md, main.go
=> Hotfix release 0.6.1

controllers/provisioners/eks/update.go
Fixes #107 
This removes the conflict with cluster-autoscaler
=> Avoid modifications to desired instances

config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, test-bdd/features/01_create.feature, test-bdd/features/04_delete.feature
This adds the missing codegen tag for controller-gen 0.2.9 and adds the fargate BDD create/delete at the top of the feature to optimize run time.
=> Missing codegen changes, bdd fixes

test-bdd/main_test.go
conditions syntax was always checking for true instead of actual condition declared in syntax
=> Fix BDD syntax for Conditions

controllers/provisioners/eks/eks.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go
This will help to restrict daemonset/pod using node label selector
=> adding lifecycle node label

api/v1alpha1/instancegroup_types.go, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/providers/aws/aws.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, docs/EKS.md
Fixes #158 
This adds the "Name" field to the UserData stage struct.
=> Add "Name" Field to UserDataStage

controllers/common/utils.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, docs/EKS.md
This adds support for base64 data in userData.[].Data
TBD
=> support base64 payload in userData

api/v1alpha1/instancegroup_types.go, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/provisioners/eks/helpers.go, docs/EKS.md
Closes #177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keikoproj/instance-manager/178)
=> Make Notification and Role ARNs optional for lifecycle hooks

controllers/provisioners/eks/eks.go, controllers/provisioners/eks/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go
Closes #180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keikoproj/instance-manager/183)
=> Add capability to automatically add cluster autoscaler ASG tags

CHANGELOG.md, README.md, main.go
=> release 0.9.0

controllers/providers/aws/aws.go, controllers/provisioners/eks/scaling/launchtemplate.go, controllers/provisioners/eks/scaling/launchtemplate_test.go, controllers/provisioners/eks/update_test.go
=> mutate TargetResource after calling ModifyLaunchTemplate

CHANGELOG.md, README.md, main.go
=> release 0.9.1

controllers/providers/aws/aws.go, controllers/provisioners/eks/upgrade.go
=> Get launchID from scaling group

.github/workflows/push.yml
=> Fix special character in GH Workflow

.github/workflows/push.yml
=> Fix image repository location on dockerhub for GH workflow

.travis.yml, CHANGELOG.md, README.md, main.go
Signed-off-by: Eytan Avisror <eytan.avisror@hotmail.com>
=> release 0.9.2

controllers/provisioners/eks/helpers.go
=> Add Pre/PostBootstrap for Windows Nodes

.github/workflows/functional-test.yaml, .github/workflows/push.yml, .github/workflows/unit-test.yml, test-bdd/features/04_delete.feature
Adds to #137 
This adds some tweaks / improvements to existing github actions and moves execution of BDD to Github Actions on PR comments '/ok-to-test' and every night on 23:05 PST on master branch.
=> Add Github Action for BDD

api/v1alpha1/instancegroup_types.go, api/v1alpha1/instancegroup_types_test.go, controllers/providers/aws/aws.go
=> feat: add support for new volume types

controllers/providers/aws/aws.go, controllers/provisioners/eks/scaling/launchtemplate.go, controllers/provisioners/eks/scaling/launchtemplate_test.go, controllers/provisioners/eks/update.go
=> fix: set latest launch template version when creating a new version

config/rbac/role.yaml, controllers/instancegroup_controller.go
Add necessary permission for watching namespaces to Role. 
=> fix: add missing namespace watch permission

Dockerfile, Makefile, go.mod
=> update to go 1.15

api/v1alpha1/instancegroup_types.go, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/instancegroup_controller.go, controllers/providers/aws/aws.go, controllers/providers/kubernetes/crd.go, controllers/providers/kubernetes/utils.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/update.go, controllers/provisioners/eks/update_test.go, controllers/provisioners/eksfargate/eksfargate.go
=> fix: upgrade resource replacement loop

controllers/provisioners/eks/update.go
=> fix: address nil pointer when switching between launch config to template

docs/INSTALL.md
* Fixed few typos.
* Formatting.
=> Docs update

controllers/providers/kubernetes/utils.go
=> fix: Allow kubeconfig chaining for local-mode

CHANGELOG.md, README.md, main.go
=> Release: 0.10.1

.github/workflows/functional-test.yaml, .github/workflows/unit-test.yml
=> fix: functional test setup broken

CHANGELOG.md, README.md, main.go
- Functional-test fixes (#272, #276)
- Add build stage to Github Actions (#281)
- Add locking to Namespaces map access (#279)
- annotation for IRSA enabled nodes (#271)
- add image default label to nodes (#270) 
- prometheus metrics integration (#274)
- conditional default values (#273)
=> Release 0.11.0

CHANGELOG.md, README.md, main.go
- Only set restricted field to default value if none of the conditionals set it (#284)
=> release 0.11.1

CHANGELOG.md, README.md, main.go
- Warm Pool Support (#286, #290)
- Fixes for conditionals logic (#287)
- OsFamily validation (#289)
=> release 0.12.0

api/v1alpha1/instancegroup_types.go, api/v1alpha1/instancegroup_types_test.go, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/providers/aws/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, docs/EKS.md
=> feat: add support for specifying container runtime

CHANGELOG.md, README.md, main.go
=> release 0.13.0

CHANGELOG.md, README.md, main.go
=> chore: release 0.14.0

CHANGELOG.md, README.md, main.go
Signed-off-by: Venkata Gunapati <venkata_gunapati@intuit.com>
=> chore: release 0.15.0
