keikoproj/instance-manager

api/v1alpha1/instancegroup_types.go, config/crd/bases/instancemgr.orkaproj.io_instancegroups.yaml, controllers/provisioners/ekscloudformation/helpers.go, controllers/provisioners/ekscloudformation/strategy.go, controllers/provisioners/ekscloudformation/types.go, docs/04_instance-manager.yaml, docs/examples/crd-argo.yaml, docs/examples/crd-rollup.yaml, test-bdd/setup/setup.sh
Fixes #1 
- This implements concurrencyPolicy to lock currently running workflows/CR.
- Added some doc/example fixes
- Unit tests passing
- Full bdd test testing
- Manually ran rollingupgrades with InstanceGroup AMI changes and only a single CR was processed at a time.
=> CRD Strategy: implement concurrencyPolicy

docs/upgrade-manager.yaml, test-bdd/main_test.go, test-bdd/setup/setup.sh, test-bdd/templates/instance-group-crd.yaml, test-bdd/testutil/helpers.go, test-bdd/testutil/wfresource.go
Fixes #10 
Functional test will now use upgrade-manager instead of argo to rotate the nodes
- Ran test manually, passed
=> Functional Test using upgrade-manager

.travis.yml, test-bdd/templates/instance-group-crd.yaml
Fixes #15 
- Gets rid of cluster create/delete for every test (-40 minutes~)
- Make upgrade-manager post drain/kill shorter
Tests should not take more than 20 minutes now.
- Ran this on my fork - job is no longer timing out
=> Make functional test quicker

controllers/provisioners/ekscloudformation/strategy.go, controllers/provisioners/ekscloudformation/types.go
Fixes #20 
- Adds another annotation to CR that defines the scope of the concurrency lock (scaling group name).
- Tested manually to verify the bug, and the fix for the bug.
=> CRD Strategy: fix concurrency of multiple instancegroups

controllers/provisioners/ekscloudformation/bootstrap.go, controllers/provisioners/ekscloudformation/ekscloudformation.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go, controllers/provisioners/ekscloudformation/helpers.go, controllers/provisioners/ekscloudformation/types.go, docs/README.md
Fixes #26 
- Parsing of the existing `aws-auth` configmap
- Retain mapRole if it does not conflict with a node role
-- Added some unit tests
=> Retain existing aws-auth mapRoles

api/v1alpha1/instancegroup_types.go, config/crd/bases/instance-manager-configmap.yaml, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/instancegroup_controller.go, controllers/providers/aws/aws.go, controllers/provisioners/ekscloudformation/bootstrap.go, controllers/provisioners/ekscloudformation/ekscloudformation.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go, controllers/provisioners/ekscloudformation/helpers.go, controllers/provisioners/ekscloudformation/spot.go, controllers/provisioners/ekscloudformation/types.go, docs/04_instance-manager.yaml, docs/README.md, main.go, test-bdd/main_test.go
Fixes #35 
This PR adds support for spot-instances with the following implementation:
- Recommendation reconciler was added to controller to watch all events, and trigger a reconcile for any event that is with reason `SpotRecommendationGiven`, the reconciler will reverse lookup the scaling group name from the event's `involvedObject.Name`, and find the instance group name and namespace in order to trigger it's reconcile.
- aws client (asg) is now needed before context is created (for reverse lookup), we should refactor and move all of the `AwsWorker` object outside of context instead on a later PR.
- `spotPrice` can be set manually in the CR, but will always be overridden by recommendations when it exists
- when recommendations become unavailable instance group will switch back to …
=> Support Spot Instances

config/crd/bases/instance-manager-deployment.yaml, config/rbac/role.yaml, controllers/instancegroup_controller.go
Spot support was merged without the required RBAC.
=> rbac changes for spot support

controllers/providers/aws/aws.go, controllers/provisioners/ekscloudformation/ekscloudformation.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go
Fixes #24 
This PR adds distinction between UnrecoverableError and UnrecoverableDeletionError,  when an IG is deleted, if the state is `UnrecoverableError` (e.g. `ROLLBACK_COMPLETE`), it should allow the deletion of the stack, however if the stack is in `UnrecoverableDeletionError` (e.g. `DELETE_FAILED`) only a human can fix this, so stack will be in err state.
Added a test to validate this behavior
=> Deletion error state

go.mod, go.sum, vendor/github.com/keikoproj/aws-auth/pkg/mapper/configmaps.go, vendor/modules.txt
This includes a fix to aws-auth to create a configmap if it doesnt already exist.
This is good to have in case the aws-auth cm does not exist by the time instance-manager needs to upsert.
=> update aws-auth to 0.1.1

api/v1alpha1/instancegroup_types.go, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/instancegroup_controller.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go, controllers/provisioners/ekscloudformation/helpers.go, controllers/provisioners/ekscloudformation/types.go, docs/04_instance-manager.yaml, docs/examples/crd-argo.yaml, test-bdd/templates/instance-group-crd.yaml
Fixes #45 
This PR adds support for `stackNamePrefix` in the controller global config.
Created stack name is persisted in `.Status.StackName` and then only read from there.
Move `LoadControllerConfig` inside the provisioner as it's quite specific for the ekscf provisioner and that seem to make more sense inside rather then in the controller.
Future PRs will follow for documentation improvements and improvements to current unit tests which are becoming a bit brittle.
Tested this feature out manually with various scenarios, including changing the prefix and restarting the controller, everything works as expected since the stack name is now persisted in the status and is the source of truth for stack name
=> Cloudformation Stack Prefixes

config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/provisioners/ekscloudformation/ekscloudformation.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go, controllers/provisioners/ekscloudformation/strategy.go
Fixes #51 
This skips setting defaults for rollingUpdate if type is not rollingUpdate.
Added some other things that were missing
=> Fix rollingUpdate strategy being set

controllers/provisioners/ekscloudformation/ekscloudformation.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go
Currently, attach managed policy only support policy with default aws prefix `arn:aws:iam::aws:policy/`. This change will support attach managed policy which has prefix `arn:aws:iam::{account_number}:policy/`
=> Support attach policy which doesn't has default aws policy prefix

api/v1alpha1/instancegroup_types.go, config/crd/bases/instance-manager-configmap.yaml, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, config/samples/instancemgr_v1alpha1_instancegroup_with_existing_iam.yaml, controllers/provisioners/ekscloudformation/bootstrap.go, controllers/provisioners/ekscloudformation/ekscloudformation.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go, docs/04_instance-manager.yaml
fixes #56 
This implements additional configuration for the EKSCF API called `roleName` which will override the creation of a new IAM role within the cloudformation stack and instead use an existing role for the instance profile + bootstrapping.
This helps with the use case where a user does not wish to create IAM roles from within the cluster and can now provide an externally created IAM role.
In this case the IAM role provided must have the basic minimum roles in order to join the cluster, and `managedPolicies` field is not supported as the role is now essentially managed by the user and not instance-manager.
Added unit tests
=> Support for existing IAM roles

CHANGELOG.md, README.md, api/v1alpha1/instancegroup_types.go, config/crd/bases/instance-manager-configmap.yaml, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/provisioners/ekscloudformation/ekscloudformation.go, controllers/provisioners/ekscloudformation/ekscloudformation_test.go, docs/04_instance-manager.yaml
fixes #64 
This adds support for `.spec.instanceProfileName` to handle cases where the instance profile name is different than the `.spec.roleName` provided.
This PR also release 0.4.2
=> 0.4.2 - fix existing IAM support

go.mod, go.sum
Fixes #68 
Update go.mod for upgrading AWS SDK[1] for IRSA 
IRSA can then provide AWS permissions to the instance-manager controller pod that uses that service account. :-)
[1] https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html
I think the controller works well with upgrading aws-sdk-go
```
time="2019-12-05T16:22:43Z" level=info msg="reconcile started"
time="2019-12-05T16:22:43Z" level=info msg="resource document version: 12214434"
time="2019-12-05T16:22:43Z" level=info msg="resource namespace: addon-instance-manager"
time="2019-12-05T16:22:43Z" level=info msg="resource name: hello-world"
time="2019-12-05T16:22:43Z" level=info msg="resource provisioner: eks-cf"
time="2019-12-05T16:22:43Z" level=info msg="upgrade strategy: rollingupdate"
```
=> Upgrade  aws-sdk-go for IRSA

docs/README.md
At the beginning of the doc, we have the following instruction
```
cd <repository-root>  # cwd should be the root of the repository
```
The next command has the correct path for the CloudFormation template, but all of the subsequent commands have the wrong paths. This PR is to fix all the wrong paths.
=> Fixed Installation Reference Walkthrough doc to have correct paths

api/v1alpha1/instancegroup_types.go, controllers/common/utils.go, controllers/instancegroup_controller.go, controllers/provisioners/eks/upgrade.go, controllers/provisioners/eks/upgrade_test.go
This adds some defaults and early failure around missing/invalid spec fields
=> Spec validation

api/v1alpha1/groupversion_info.go, api/v1alpha1/instancegroup_types.go, controllers/providers/kubernetes/events.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/create.go, controllers/provisioners/eks/create_test.go, controllers/provisioners/eks/delete.go, controllers/provisioners/eks/delete_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/update_test.go, controllers/provisioners/eks/upgrade.go, controllers/provisioners/eks/upgrade_test.go, go.mod, go.sum
Fixes #100 
Adds basic event publishing
=> Event Publishing

controllers/common/utils.go, controllers/providers/aws/aws.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/cloud_test.go, controllers/provisioners/eks/create.go, controllers/provisioners/eks/delete.go, controllers/provisioners/eks/delete_test.go, controllers/provisioners/eks/eks.go, controllers/provisioners/eks/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/update.go
Fixes #114 
This adds pagination for DescribeLaunchConfigurations and refactors create/update/delete to properly handle launch configuration deletion.
New logic will be called on CloudDiscovery instead of during update, and will delete the oldest launch configurations per instance group outside of the newest ones according to number of default retention (default 2) - we can make this configurable in the future.
IG Deletion now simply deletes all launch configs with the resource prefix.
=> Pagination & Launch config deletion

controllers/providers/aws/aws.go, controllers/provisioners/eks/create.go, controllers/provisioners/eks/create_test.go
Ref #112 
This optimizes the Create flow to reduce number of API calls being made.
Calls removed from create flow:
- `WaitUntilInstanceProfileExists`
- `DescribeLaunchConfigurations`
- `DescribeAutoScalingGroups`
=> AWS API Optimization - Create

api/v1alpha1/instancegroup_types.go, controllers/common/utils.go, controllers/providers/aws/aws.go, controllers/providers/kubernetes/rollingupdate.go, controllers/providers/kubernetes/utils.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/update.go, controllers/provisioners/eks/update_test.go, controllers/provisioners/eks/upgrade.go, controllers/provisioners/eks/upgrade_test.go
Ref #112 
This refactors the update flow to remove redundant API calls
=> AWS API Optimization - Update

controllers/providers/aws/aws.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/create.go, controllers/provisioners/eks/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/update.go, controllers/provisioners/eks/update_test.go
Fixes #112 
This optimizes the IAM calls we make by only trying to attach managed policies if they are not attached.
=> AWS API Optimization - IAM

controllers/common/bootstrap.go, controllers/providers/aws/aws.go, controllers/provisioners/eks/delete.go, controllers/provisioners/eks/helpers.go, go.mod, go.sum, main.go
Fixes #87 
This adds caching for AWS calls
- Total calls: 1432
- Cache Hits: 1137
- Cache Misses: 295 (~20%)
- Throttled: 0
- Total calls: 1953
- Cache Hits: 1071
- Cache Misses: 882 (45%)
- Throttled: 0
=> AWS SDK Caching

.github/CODEOWNERS, config/rbac/role.yaml, controllers/common/utils.go, controllers/instancegroup_controller.go, controllers/provisioners/eks/eks.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, main.go
This bypasses the (very annoying) mechanism put forth in https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md
This will enable the instance-group controller, to label any node that has the label `node.kubernetes.io/role=role` populated, with the respective `kubernetes.io/role=role` which cannot be added during bootstrap in 1.16.
```
node-role.kubernetes.io/instance-group-1="" => added as default kubelet arguments
node.kubernetes.io/role=instance-group-1 => added as default kubelet arguments
```
```
node-role.kubernetes.io/instance-group-1="" => added as default kubelet arguments
node.kubernetes.io/role=instance-group-1 => added as default kubelet arguments
```
```
node-role.kubernetes.io/instance-group-1="" => added as …
```
=> Add kubernetes.io/role label via node reconciler

api/v1alpha1/zz_generated.deepcopy.go
PR #132 was missing the generated deepcopy changes.
=> Add missing deepcopy for suspendProcesses

controllers/providers/aws/aws.go, controllers/providers/aws/retry.go, main.go
Fixes #118 
This lowers the default retry count to a more reasonable number (50 > 12), and also makes it configurable.
=> Configurable Retries

controllers/providers/kubernetes/rollingupdate.go, docs/INSTALL.md, docs/README.md
Fixes #150 
Logging fixed after adding missing `()`
```
failed to terminate targets	{"reason": "AccessDenied: User: <reducted> is not authorized to perform: autoscaling:TerminateInstanceInAutoScalingGroup on resource:<reducted>\n\tstatus code: 403, request id: 3d1d3fab-e282-42f6-90dc-61699b9397f7", "scalinggroup": "instancemgr-dev-instance-manager-my-instance-group-2", "targets": ["i-025a0d00ddadf24b8"]}
```
Fixed docs for IAM permissions needed
=> doc & logging fixes

controllers/common/utils.go, controllers/instancegroup_controller.go
Fixes #151 
This modifies the way we set/remove finalizers in order to move to a uniform finalizer for all provisioners without breaking compatibility
- SetFinalizer will add the new finalizer "finalizer.instancegroups.keikoproj.io" (which does not mention provisioner)
- Finalize will remove ALL finalizers - given this is an owned resource that should be OK.
=> uniform finalizer

api/v1alpha1/instancegroup_types.go, controllers/providers/aws/aws.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/cloud_test.go, controllers/provisioners/eks/create.go, controllers/provisioners/eks/create_test.go, controllers/provisioners/eks/delete_test.go, controllers/provisioners/eks/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, controllers/provisioners/eks/state_test.go, controllers/provisioners/eks/update.go, controllers/provisioners/eks/update_test.go, controllers/provisioners/eks/upgrade_test.go, docs/EKS.md, docs/INSTALL.md, main.go
Fixes #156 
This adds support for using "Name" tag of resource instead of ID for Subnets & Security Groups if provided.
=> Resolve security groups / subnets by Name tag

controllers/common/utils.go, controllers/instancegroup_controller.go, controllers/interface.go, controllers/providers/aws/aws.go, controllers/provisioners/config.go, controllers/provisioners/config_test.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/cloud_test.go, controllers/provisioners/eks/create.go, controllers/provisioners/eks/create_test.go, controllers/provisioners/eks/delete.go, controllers/provisioners/eks/delete_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, controllers/provisioners/eks/scaling/interface.go, controllers/provisioners/eks/scaling/launchconfig.go, controllers/provisioners/eks/scaling/launchconfig_test.go, controllers/provisioners/eks/state.go, controllers/provisioners/eks/update.go, controllers/provisioners/eks/update_test.go, controllers/provisioners/eksfargate/eksfargate.go, controllers/provisioners/eksfargate/eksfargate_test.go, controllers/provisioners/eksmanaged/eksmanaged.go, controllers/provisioners/provisioners.go, main.go
Ref #17 
Fixes #163 
This abstracts the concrete launch configuration state/provisioner into an interface called ScalingConfiguration which can create multiple types of configurations.
Added the implementation of a LaunchConfiguration type and refactored the code & tests to use that instead of existing implementation.
This will allow to create a new ScalingConfiguration type later called LaunchTemplate
=> Refactor - Abstract ScalingConfiguration

controllers/instancegroup_controller.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/eks.go, controllers/provisioners/provisioners.go, main.go
closes #116 
This takes a new flag `--config-retention` that determines how many launch configurations we retain - defaults to 2.
=> make config retention configurable

api/v1alpha1/instancegroup_types.go, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/provisioners/eks/eks.go
Fixes #170 
Adds strategy & provisioner as status fields so that it's never missing in printer columns when using configmap defaults
=> add strategy & provisioner to status

controllers/provisioners/eks/create_test.go, controllers/provisioners/eks/eks.go, controllers/provisioners/eks/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, controllers/provisioners/eks/update_test.go
This PR leverages the os-family annotation introduced in #186 to support [BottleRocket](https://aws.amazon.com/bottlerocket/) AMIs on EKS self-managed node groups. 
=> feat: Add BottleRocket os family

controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/create.go
Fixes #202 
For IAM role/profile creation/deletion, this uses an MD5 hash of the resource name if the resource name is too long
=> ManagedRole: use MD5 when name is exceeding limit

controllers/provisioners/eks/upgrade.go
Fixes #205 
Adds a nil check to cover this scenario, in this case if the instance launch configuration / template is nil, it means it needs to be rotated.
=> Fix Nil Pointer when switching to LaunchTemplate via RollingUpdate

.github/workflows/push.yml, .github/workflows/test.yml
Closes #191 
Partially implements #137
This PR adds two GitHub actions - one for running unit tests, and another for publishing images. 
The image publication adds several new features above and beyond the existing image publication today:
- MultiArch images are now published (see [example](https://hub.docker.com/layers/jbacklegalzoom/instancemgr/pr-1/images/sha256-502fb4cd61290eb91c2cc9f63794c971b2cf73859eee2770d2222359411d66c4?context=repo))
- PR images are automatically published
- Images can easily be published to multiple repos - this PR adds GitHub container registry, which does not have any limits on downloading containers. 
Before any merge, this would needs secrets added to this repo for pushing to GHCR and DockerHub
=> Add Github Actions for unit test and image publication

api/v1alpha1/instancegroup_types.go, config/crd/bases/instancemgr.keikoproj.io_instancegroups.yaml, controllers/providers/kubernetes/crd.go, controllers/providers/kubernetes/utils.go, controllers/provisioners/eks/update.go, docs/INSTALL.md
Fixes #211 
This marks rotationNeeded if the custom resource for node rotation is still active.
Without this, we are exposed to a race condition where if during an upgrade all nodes are ready we may mark it completed prematurely.
This requires adding another status field to cache the upgrade resource's namespace
TBD:
=> Fix premature upgrade completion

Dockerfile
The explicit GOARCH variable in the Dockerfile causes ARM images to contain an AMD64 executable. This variable is unnecessary, since go will inspect the system to figure out what architecture it is running in. 
=> fix: remove explicit architecture in go build

api/v1alpha1/instancegroup_types.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/create.go, controllers/provisioners/eks/create_test.go, controllers/provisioners/eks/scaling/interface.go, controllers/provisioners/eks/scaling/launchconfig.go, controllers/provisioners/eks/scaling/launchtemplate.go
Fixes #223 
Background: This bug only happens on the creation flow - when the launch template is created, but the scaling group fails to create due to a launch template problem (e.g. bad AMI, missing permission, etc). In this case we never move on to update flow since the scaling group never gets created, and there is no logic to handle the case where the launch template already exist but the scaling group does not - so we enter an endless loop of creating new configurations until the CR value is fixed.
Desired behavior: The behavior should be that we create a scaling config once, if the downstream operation (e.g. creating a scaling group) fails due to a bad config, we should only create a new config/config version if there is a diff …
=> Avoid launch template creation loop

.github/workflows/functional-test.yaml, README.md
It seems you cannot publish images from fork based PRs, hence removing comment trigger for now.
=> Remove Github Actions comment trigger

controllers/instancegroup_controller.go, controllers/providers/kubernetes/utils.go, controllers/provisioners/eks/eks.go, go.mod
Fixes #235 
- Moves setting of config hash up to controller level, will now unset configHash field if configmap is nil/empty/does not exist.
- Refactors namespace exclusion logic into IsNamespaceExcluded method
- Refactors `UpdateStatus` to use patch instead of update, in order avoid metadata changes causing a reconcile loop - in k8s 1.18 managedFields was introduced along with a `time` field which causes this problem when using Update method. For now this implements a custom StatusPatch, in the future we might want something similar to #240 
@backjo
=> remove config hash when namespace is excluded

.github/DEVELOPER.md, test-bdd/main_test.go
This fixes an issue where if the bdd fails it does not clean up properly by deleting the config map while the instance group is still being deleted - this leaves the controller in a bad state.
This is prevented by leaving the configmap deletion to the very end of deleteAll()
Also added resource kind to logging and made waiter polling interval shorter
=> fix: bdd cleanup timing bug

controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go
Some whitespaces were introduced in #216 that cause a rolling upgrade when controller is upgraded.
This PR removes the whitespaces to maintain same userData if spec did not change.
=> fix: remove whitespaces causing rolling upgrade

controllers/provisioners/eks/update.go
=> fix: guard cast of launchtemplate with type check

api/v1alpha1/instancegroup_types.go, controllers/provisioners/eksfargate/eksfargate.go, controllers/provisioners/eksfargate/eksfargate_test.go, controllers/provisioners/eksmanaged/eksmanaged.go
=> fix: validation for provisioner type

README.md, controllers/providers/aws/aws.go, controllers/provisioners/eksmanaged/eksmanaged.go, docs/EKS.md
=> fix: refactor eks-managed GetLabelsUpdatePayload

.github/workflows/unit-test.yml
=> fix: run build on unit test task

controllers/instancegroup_controller.go, controllers/provisioners/config.go, main.go
Fixes #278 
This adds a read lock/unlock when accessing Namespaces map
=> fix: add locking to map access

controllers/provisioners/config.go, controllers/provisioners/config_test.go
=> fix: only set restricted field to default value if none of the conditionals set it

controllers/provisioners/config.go, controllers/provisioners/config_test.go
this PR fixes a few bugs in the conditional rule logic for fields that can be merged, notably:
1. On 'merge' fields, the conditional value was being merged into the resource value before the default value was merged. This would cause the default value to take priority over the conditional value, which was not intended.
1. On 'merge' fields, the conditional value was not being set if a conflict was not present. 
1. On 'mergeOverride' fields, the conditional value was replacing the default value. Now, it is merged with the default value, with the conditional value taking priority. 
It also allows the userData field to be merged on the name key.
=> fix: correct merge logic for conditional rules

controllers/provisioners/eks/eks.go, controllers/provisioners/eks/helpers_test.go
=> fix: add validation for OsFamily annotation value

controllers/provisioners/eks/helpers.go, docs/EKS.md
=> feat: Support Windows for Warm Pools

controllers/provisioners/eks/cloud.go
Fixes #311 
This PR moves the instance type discovery above an early exit for non-provisioned IGs (https://github.com/keikoproj/instance-manager/pull/312/files#diff-d02fec8ce89d970a6731dc6003cb0f6f8c4cb452daa1ad45c5fd2691fd75afa3R187).
=> fix: Set InstanceTypes before provisioned early exit

CHANGELOG.md, README.md, main.go
- fix: Set InstanceTypes before provisioned early exit (#312) 
- refactor: awsprovider file restructure (#296)
- feat: add support for instance metadata options (#305)
- fix: Ignore mixedInstancePolicy if type is LaunchConfig (#303)
- fix: add sorting when resolving securitygroups/subnets (#302)
=> release 0.12.1

controllers/providers/aws/aws.go, controllers/providers/aws/ec2.go, controllers/providers/aws/eks.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/eks_test.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, controllers/provisioners/eks/scaling/launchconfig_test.go, main.go
Fixes #306 
This PR uses the payload from DescribeCluster to feed CA & API endpoint directly to userdata in order to avoid making those calls and potentially getting throttled on user-data.
This also fixes the argument passing in the case of Windows so that we wrap the Kubelet arguments same as we do for Linux
=> Pass API Endpoint & CA Cert directly to bootstrap.sh

controllers/provisioners/eks/scaling/launchconfig_test.go, controllers/provisioners/eks/update.go
Fix #308 
This fixes a bug where controller-added tags are not evaluated when reconciling.
=> fix: evaluate controller-added ec2 tags

controllers/providers/aws/eks.go, controllers/providers/aws/eks_test.go
=> fix: calculate cluster dns correctly for non /16 blocks

controllers/providers/aws/aws.go, controllers/provisioners/eks/cloud.go, controllers/provisioners/eks/cloud_test.go, controllers/provisioners/eks/eks_test.go
=> fix: check architecture when considering similar instance types in the same family

controllers/instancegroup_controller.go, controllers/provisioners/eks/eks.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go, controllers/provisioners/provisioners.go, main.go
The Windows EKS bootstrap script currently contains a bug related to ServiceCidr calculations when passing in ClusterCA and APIEndpoint information - see https://github.com/awslabs/amazon-eks-ami/issues/805. Until the bootstrap script allows us to provide the ServiceCIDR, we should stop passing in the ClusterCA and Endpoint information to avoid incorrect CIDRs from being calculated.
=> Stop passing in ClusterCA and Endpoint information for Windows nodes

controllers/common/utils.go, controllers/provisioners/eks/helpers.go, controllers/provisioners/eks/helpers_test.go
=> fix: don't set max pods above kubernetes recommended limit

.github/workflows/unit-test.yml, Dockerfile, go.mod, go.sum
See https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/ for more info. TL;DR - this change uses Go's native cross-compilation inside the Docker build to minimize the amount of time spent using emulation. 
=> chore: update go, improve cross-compilation in docker

.github/workflows/unit-test.yml, controllers/providers/kubernetes/utils.go, controllers/provisioners/eks/eks_test.go
=> fix: use non-deprecated CRD api

test-bdd/features/01_create.feature, test-bdd/templates/instance-group-crd.yaml, test-bdd/templates/instance-group.yaml
Ref #310 
Seems like most functional test failures are around failure to acquire a spot price for an instance.
It also adds a dependency on another controller (minion-manager)
This PR removes testing for spot from functional test
=> Remove spot dependency from functional test

api/v1alpha1/instancegroup_types.go, api/v1alpha1/instancegroup_types_test.go, controllers/providers/aws/aws.go, controllers/provisioners/eks/helpers.go
Fixes #373 
Feedback is welcome.
```
coverage: 83.8% of statements
ok      github.com/keikoproj/instance-manager/controllers/provisioners/eksmanaged       0.057s  coverage: 83.8% of statements
=== RUN   TestInstanceGroupSpecValidate
=== RUN   TestInstanceGroupSpecValidate/eks-fargate_with_managed_strategy
=== RUN   TestInstanceGroupSpecValidate/eks-bogus_provisioner
=== RUN   TestInstanceGroupSpecValidate/eks-fargate_with_bad_strategy
=== RUN   TestInstanceGroupSpecValidate/eks_with_empty_strings_in_licenseSpecifications
=== RUN   TestInstanceGroupSpecValidate/eks_with_invalid_licenseSpecification
=== RUN   TestInstanceGroupSpecValidate/eks_with_invalid_container_runtime
=== RUN   TestInstanceGroupSpecValidate/eks_with_valid_Placement
=== RUN …
```
=> fix/373 Replace ARN format validation procedure

CHANGELOG.md, README.md, main.go
* Fix incorrect counter name (#409)
* Bump sigs.k8s.io/controller-runtime from 0.12.1 to 0.12.3 (#400)
* Bump github.com/prometheus/client_golang (#403)
* Bump github.com/onsi/gomega from 1.27.10 to 1.28.0 (#404)
* Bump crazy-max/ghaction-docker-meta from 1 to 5 (#407)
* Bump golang.org/x/net from 0.12.0 to 0.17.0 (#408)
* Bump docker/build-push-action from 2 to 5 (#406)
* Bump docker/login-action from 1 to 3 (#405)
* Bump github.com/aws/aws-sdk-go from 1.45.14 to 1.45.19 (#402)
* Bump codecov/codecov-action from 1 to 3 (#395)
* Bump docker/setup-qemu-action from 1 to 3 (#397)
* Bump docker/setup-buildx-action from 1 to 3 (#394)
* Bump actions/setup-go from 2 to 4 (#393)
* Bump actions/checkout from 2 to 4 (#396)
* Add dependabot configuration (#392)
* Update aws-auth and aws-sdk-go-cache …
=> Release v0.17.0

.github/workflows/unit-test.yml, .golangci.yml, Makefile
This PR implements the changes described in issue #464 to migrate from the deprecated golint to the more modern golangci-lint tool.
- Added a minimal `.golangci.yml` configuration file with essential linters
- Updated the `Makefile` to use golangci-lint instead of golint
- Modified the GitHub workflow to install and run golangci-lint
- Made linting errors non-blocking initially to allow for a gradual transition
This implementation takes a gradual approach to the migration:
1. Linting errors are reported but don't fail builds during the transition
2. Only a minimal set of linters is enabled initially (govet, gosimple, ineffassign)
3. The infrastructure is in place to enable more linters in future PRs
- Verified that the linting command works correctly locally
- Confirmed that the linting …
=> chore: switch from golint to golangci-lint

.github/workflows/push.yml, Dockerfile
This PR enhances the Docker image build process to improve build speed, reliability, and standards compliance.
- Reorganized the Docker image build workflow to run platform builds in parallel
- Split the process into separate build and push jobs for better performance
- Added proper caching configuration to speed up subsequent builds
- Added proper ARG declarations in the Dockerfile to receive build arguments
- Improved label formatting with proper quotes and values
- Implemented standardized OCI label generation via docker/metadata-action
- Added proper image versioning and timestamps
- Improved conditional image pushing (skips on PRs)
- Added proper layer caching across builds
- Ensured image metadata is properly populated
The changes have been manually tested to ensure:
1. Container …
=> Improve Docker Image Build Process

.github/workflows/image-push.yml
This PR resolves authentication issues with GitHub Container Registry (GHCR) in our Docker image build workflow.
- Improved authentication with GitHub Container Registry using appropriate credentials
- Updated container registry permissions in the workflow configuration
- Fixed build provenance attestation to properly work with both registries
The previous image build improvements (PR #475) were unable to properly authenticate with GHCR, resulting in 403 Forbidden errors when attempting to push images. This PR specifically addresses those authentication issues.
The workflow has been tested to verify:
1. Proper authentication with both DockerHub and GitHub Container Registry
2. Correct image tagging and pushing to both registries
3. Generation of build provenance attestations
Builds on and …
=> Fix GitHub Container Registry Authentication

.github/workflows/functional-test.yaml, .github/workflows/golangci-lint.yml, .github/workflows/image-push.yml, .github/workflows/unit-test.yml, Dockerfile
This PR enhances GitHub Actions workflows with detailed permission documentation and fixes the Dockerfile syntax to eliminate linting warnings. It also ensures proper image build and provenance attestation.
- Added comprehensive documentation comments for all workflow permissions
- Improved Docker metadata handling with consistent ID references
- Ensured proper permissions for GitHub Container Registry (GHCR) access
- Added attestation generation for both Docker Hub and GHCR images
- Fixed workflow job dependencies and naming for better clarity
- Fixed casing of Dockerfile instructions (`as` → `AS`) to eliminate linting warnings
- Ensure consistent syntax throughout the Dockerfile
- Added detailed comments explaining each permission's purpose
- Standardized permission documentation across …
=> Improve GitHub Actions Workflows for Docker Image Building

.github/workflows/image-push.yml
This PR fixes the image-push workflow that was failing with the error "No credentials found for registry keikoproj". The issue was caused by not explicitly specifying the Docker registry, causing Docker to interpret "keikoproj" as a registry name rather than an organization on DockerHub.
- Added explicit `docker.io/` prefix to all Docker image references in the workflow
- Updated build outputs configuration to use the fully qualified image name
- Updated attestation subject names to use consistent registry references
The image-push GitHub Action workflow should now successfully authenticate and push images to both DockerHub and GitHub Container Registry.
=> Fix Docker Registry Authentication in GitHub Actions

.github/workflows/image-push.yml
This PR addresses two issues with the container image workflow:
1. **Registry Authentication**: Fixes the image-push workflow that was failing with the error "No credentials found for registry keikoproj". The issue was caused by not explicitly specifying the Docker registry, causing Docker to interpret "keikoproj" as a registry name rather than an organization on DockerHub.
2. **Multi-arch Image OCI Annotations**: Enhances container metadata by properly configuring the OCI annotations in the manifest list for multi-architecture images, addressing GitHub Packages warnings about missing metadata.
- Added explicit `docker.io/` prefix to all Docker image references in the workflow
- Added complete set of OCI annotations to properly document the container images
- Configured the manifest list …
=> Fix Docker Registry Authentication and OCI Annotations for Multi-arch Images

.github/workflows/image-push.yml
This PR addresses two issues with the container image workflow:
1. **Registry Authentication**: Fixes the image-push workflow that was failing with the error "No credentials found for registry keikoproj" by explicitly specifying the Docker registry.
2. **Multi-arch Image Annotations**: Adds proper annotations to multi-architecture container images using the correct `annotation-index` syntax, addressing the GitHub Packages warning about missing image description.
- Added explicit `docker.io/` prefix to all Docker image references
- Implemented the recommended `annotation-index` syntax for multi-arch manifests
- Added comprehensive OCI annotations (description, license, source, etc.)
- Disabled duplicate provenance to avoid conflicts with the dedicated attestation actions
- The image-push …
=> Fix Docker Registry Authentication and Multi-arch Image Annotations

.github/workflows/image-push.yml, Makefile
This PR enhances our container image builds with proper OCI metadata and improved versioning to better support multi-architecture images and provide clearer traceability.
1. **GitHub Actions Workflow**:
- Added explicit `docker.io/` prefix to all Docker image references to fix registry authentication
- Implemented proper annotation-index syntax for multi-architecture manifest annotation
- Fixed metadata placeholders to use GitHub context variables that properly resolve
2. **Makefile**:
- Added OCI label support to local container builds
- Improved versioning with `INSTANCEMGR_TAG` that includes:
- Latest Git tag (e.g., v0.19.0)
- Short commit SHA (e.g., 9835017)
- Dirty flag (-dirty) when there are uncommitted changes
- Container images now display proper metadata in both DockerHub and …
=> Improve Container Image OCI Metadata and Versioning

.github/workflows/image-push.yml
In the `merge-and-push` job, the `docker/build-push-action@v6` step was missing the `file: ./Dockerfile` parameter that specifies the location of the Dockerfile. This parameter was correctly specified in the `build-image` job but was missing in the final push step.
Added the missing `file: ./Dockerfile` parameter to the `Create manifest list and push` step in the `merge-and-push` job, allowing the action to locate the Dockerfile during the build process.
- This change can be verified when the workflow runs on this branch
=> fix: add back file pointing to dockerfile

.github/workflows/image-push.yml
The GitHub Actions workflow to build and push Docker images was failing with the error:
```
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```
The `merge-and-push` job was missing the `actions/checkout@v4` step, so the repository content (including the Dockerfile) wasn't available in this job's runner environment. In GitHub Actions, each job runs in a completely fresh environment, requiring explicit repository checkout.
Added the `actions/checkout@v4` step to the beginning of the `merge-and-push` job to ensure the Dockerfile and other repository files are available during the Docker build process.
This change can be verified when the workflow runs on this branch.
=> fix: add checkout step to merge-and-push job in workflow

.github/workflows/functional-test.yaml, .github/workflows/unit-test.yml
This PR updates the runner image for all relevant GitHub Actions workflows to use `ubuntu-latest` instead of the deprecated `ubuntu-20.04`.
See https://github.com/actions/runner-images/issues/11101 for more details.
- `.github/workflows/unit-test.yml`: `runs-on` updated from `ubuntu-20.04` to `ubuntu-latest`
- .`github/workflows/functional-test.yaml`: `runs-on` updated from `ubuntu-20.04` to `ubuntu-latest` (if previously present; now confirmed as `ubuntu-latest`)
- [GitHub Actions is deprecating the ubuntu-20.04 runner image](https://github.com/actions/runner-images/issues/11101)
- Ensures continued support and security updates for CI workflows
- Follows best practices for open-source and Kubernetes-related projects
=> fix: update GHA runner image to ubuntu-latest

.github/workflows/image-push.yml
This PR updates the `.github/workflows/image-push.ym`l workflow to:
- Use the `${{ github.event.repository.name }}` variable instead of the hardcoded `instance-manager` string, making the workflow portable and reusable.
- Add a step with `softprops/action-gh-release` to automatically update the GitHub Release with Docker image links and attestation information for release tags.
**Why?**
- Easier to copy and maintain workflows across multiple repos.
- Reduces risk of copy-paste errors.
- Improves release transparency and user experience.
=> ci: use repo name variable and add release update in image-push workflow

.github/workflows/image-push.yml
This PR updates the image-push.yml workflow to ensure that Docker image links, pull commands, and attestation references in GitHub Release notes use the correct Docker tag (without the "v" prefix).
- **Added a step** to extract the primary Docker tag from the output of `docker/metadata-action` (which automatically strips the "v" from tags like `v0.19.0` to produce `0.19.0`).
- **Updated the release notes** (via `softprops/action-gh-release`) to use this tag for:
- DockerHub and GHCR links
- Example `docker pull` commands
- Attestation references
- Previously, the release notes used `${{ github.ref_name }}` which included the "v" prefix (e.g., `v0.19.0`), resulting in incorrect pull commands and links.
- This change ensures users always see accurate instructions and links that match the …
=> fix: use Docker metadata-action tag for release notes
